imports:
  commons: ../commons.yml
  transactionCommons: commons.yml

types:
  BasePackageTransaction:
    extends: transactionCommons.BaseTransaction
    properties:
      PackageId: commons.PackageId

  CreatePackageTransaction:
    extends: BasePackageTransaction
    properties:
      parent: optional<commons.PackageId>
      packageName: string

  RenamePackageTransaction:
    extends: BasePackageTransaction
    properties:
      newPackageName: string

  DeletePackageTransaction:
    extends: BasePackageTransaction
    properties: {}

  ReorderPackagesTransaction:
    extends: BasePackageTransaction
    properties:
      newOrder: list<commons.PackageId>

  ReorderEndpointsTransaction:
    extends: BasePackageTransaction
    properties:
      newOrder: list<commons.EndpointId>

  ReorderTypesTransaction:
    extends: BasePackageTransaction
    properties:
      newOrder: list<commons.TypeId>

  ReorderErrorsTransaction:
    extends: BasePackageTransaction
    properties:
      newOrder: list<commons.ErrorId>
