# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: commons.yml
types:
  EnvironmentId: string
  Environment:
    extends: commons.WithDocs
    properties:
      id: EnvironmentId
      name: commons.Name
      url: string
