types:
  SeedWorkspaceConfiguration:
    properties:
      irVersion: string
      language: optional<Language>
      defaultOutputMode: OutputMode
      generatorType: GeneratorType
      docker: string
      dockerCommand: optional<DockerCommand>
      fixtures:
        type: optional<map<string, list<FixtureConfigurations>>>
      scripts: optional<list<ScriptConfig>>
      allowedFailures: 
        type: optional<list<string>>
        docs: | 
          List any fixtures that are okay to fail. For normal fixtures 
          just list the fixture name. For configured fixture list {fixture}:{outputFolder}.
      features: 
        type: GeneratorFeatureMatrix

  DockerCommand: 
    discriminated: false
    union: 
      - string
      - list<string>

  ScriptConfig:
    properties:
      docker: string
      commands: list<string>

  Language:
    enum:
      - python
      - java
      - typescript
      - go

  GeneratorType:
    enum:
      - SDK
      - Model
      - Server
      - Documentation

  FixtureConfigurations:
    properties:
      customConfig: unknown
      outputFolder: string
      outputVersion: optional<string>
      outputMode: 
        type: optional<OutputMode>
        docs: Overrides the default output mode
  
  OutputMode: 
    enum: 
      - github
      - local_files
      - publish
  
  GeneratorFeatureMatrix: 
    properties: 
      whitelabel: 
        type: boolean
        docs: | 
          Whether the generator supports reading the whitelable configuration. 
          If true, the generator will not mention `fern` in the hader of the 
          generated code. 

          Instead of `This file was auto-generated by Fern from our API Definition`, 
          the header will read `This file was auto-generated from our API Definition`.
