types:
  SeedWorkspaceConfiguration:
    properties:
      irVersion: string
      language: optional<Language>
      generatorType: GeneratorType
      docker: string
      dockerCommand: optional<string>
      fixtures:
        type: optional<map<string, list<FixtureConfigurations>>>
      scripts: optional<list<ScriptConfig>>

  ScriptConfig:
    properties:
      docker: string
      commands: list<string>

  Language:
    enum:
      - python
      - java
      - typescript
      - go

  GeneratorType:
    enum:
      - SDK
      - Model
      - Server
      - Documentation

  FixtureConfigurations:
    properties:
      customConfig: unknown
      outputFolder: string
