changesetBaseRefs:
  - main
  - origin/main

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  fern-fern:
    npmRegistryServer: "https://npm.buildwithfern.com/"

packageExtensions:
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: "*"
  "@blueprintjs/stylelint-plugin@*":
    dependencies:
      tslib: "*"
  chalk@*:
    dependencies:
      "#supports-color": "npm:supports-color@9.2.2"
  debug@*:
    dependencies:
      supports-color: ^8.1.1
  docsify-cli@*:
    dependencies:
      ansi-colors: "*"
      y18n: "*"
  docsify-server-renderer@*:
    dependencies:
      marked: "*"
      prismjs: "*"
      strip-indent: 3.0.0
  follow-redirects@*:
    dependencies:
      debug: "*"
  inquirer-file-tree-selection-prompt@*:
    dependencies:
      inquirer: ^8.0.0
  postcss-scss@*:
    dependencies:
      postcss: "*"

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.4.0.cjs
