changesetBaseRefs:
  - main
  - origin/main

nodeLinker: pnp

npmScopes:
  fern-fern:
    npmRegistryServer: "https://npm-dev.buildwithfern.com/"

packageExtensions:
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: "*"
  "@blueprintjs/stylelint-plugin@*":
    dependencies:
      tslib: "*"
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  debug@*:
    dependencies:
      supports-color: "*"
  docsify-cli@*:
    dependencies:
      ansi-colors: "*"
      y18n: "*"
  docsify-server-renderer@*:
    dependencies:
      marked: "*"
      prismjs: "*"
      strip-indent: 3.0.0
  follow-redirects@*:
    dependencies:
      debug: "*"
  inquirer-file-tree-selection-prompt@*:
    dependencies:
      inquirer: ^8.0.0
  postcss-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
