packages:     
  - "packages/**"
  - "!packages/**/lib"
  - "!packages/**/dist"
  - "!packages/**/generated"
  - "generators/**"
  - "!generators/**/lib"
  - "!generators/**/dist"
  - "!packages/cli/cli/dist/dev"
  - "!packages/cli/cli/dist/prod"