service:
  auth: false
  base-path: "/{serviceParam}"
  path-parameters:
    serviceParam: string
  endpoints:
    post:
      path: "/{endpointParam}"
      path-parameters:
        endpointParam: integer
      method: POST
