openapi: 3.0.1
info:
  title: auth-environment-variables
  version: ''
paths:
  /apiKey:
    get:
      description: GET request with custom api key
      operationId: service_getWithApiKey
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-FERN-API-KEY
