# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: commons.yml
types:
  Environments:
    properties:
      defaultEnvironment: optional<Environment>
      otherEnvironments: list<Environment>
  Environment:
    extends: commons.WithDocs
    properties:
      name: commons.Name
      url: string
