version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  lint:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint:monorepo
          command: yarn lint:monorepo
      - run:
          name: Check root package
          command: yarn root-package:check
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: lint:eslint
          command: yarn lint:eslint
      - run:
          name: lint:style
          command: yarn lint:style
      - run:
          name: Generate Fern JSON Schema
          command: yarn generate-json-schema
      - run:
          name: fern check
          command: npx fern check
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff --exit-code

  compile-and-test:
    # this is machine because of the docker-utils tests
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests
          command: yarn test --ci
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff --exit-code

  ete-tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Run ETE tests
          command: yarn test:ete
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff --exit-code

  live-test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Live Test (prod)
          command: |
            yarn workspace @fern-api/cli dist:cli:prod
            cli_path="$(yarn workspace @fern-api/cli bin fern:prod)"
            ./scripts/live-test.sh "$cli_path"

  live-test-dev:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Live Test (dev)
          command: |
            yarn workspace @fern-api/cli dist:cli:dev
            cli_path="$(yarn workspace @fern-api/cli bin fern:dev)"
            ./scripts/live-test.sh "$cli_path"

  publish-dev:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Print version
          command: |
            git_version="$(./scripts/git-version.sh)"
            echo Publishing version: "${git_version}"
      - run:
          name: Add version to package.json's
          command: |
            git_version="$(./scripts/git-version.sh)"
            yarn mrlint version "$git_version"
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish all packages
          command: yarn run publish --tag next
      - run:
          name: Publish fern-api-dev CLI
          command: yarn workspace @fern-api/cli publish:cli:dev --access restricted

  publish:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Print version
          command: |
            git_version="$(./scripts/git-version.sh)"
            echo Publishing version: "${git_version}"
      - run:
          name: Add version to package.json's
          command: |
            git_version="$(./scripts/git-version.sh)"
            yarn mrlint version "$git_version"
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish all packages
          command: yarn run publish
      - run:
          name: Publish fern-api-dev CLI
          command: yarn workspace @fern-api/cli publish:cli:dev --access restricted
      - run:
          name: Publish fern-api CLI
          command: yarn workspace @fern-api/cli publish:cli:prod

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - compile-and-test:
          filters:
            tags:
              only: /.*/

      - ete-tests:
          filters:
            tags:
              only: /.*/
          context:
            - auth0-dev

      - live-test-dev:
          filters:
            branches:
              only: main
          context:
            - auth0-dev

      - live-test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          context:
            - auth0-dev

      - publish-dev:
          filters:
            branches:
              only: main
          requires:
            - lint
            - compile-and-test
            - ete-tests
          context:
            - npm
            - auth0-dev

      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - lint
            - compile-and-test
            - ete-tests
            - live-test
          context:
            - npm
            - auth0-dev
