version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  check:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Run code-generation
          command: npx fern-api@0.0.54 generate
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint:monorepo
          command: yarn lint:monorepo
      - run:
          name: lint:eslint
          command: yarn lint:eslint
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: |
            yarn depcheck
            yarn dlx @yarnpkg/doctor
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Build fern-typescript docker (for ETE tests)
          command: yarn workspace fern-typescript dockerTagLocal
      - run:
          name: Run tests
          command: yarn test --ci
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff

  publish:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Run code-generation
          command: npx fern-api@0.0.54 generate
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Add version to package.json's
          command: yarn mrlint version $(git tag --points-at HEAD)
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish all packages
          command: yarn run publish
      - run:
          name: Publish fern-typescript docker
          command: |
            projectVersion=$(git tag --points-at HEAD)
            yarn workspace fern-typescript dockerTagVersion
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag fern-typescript:"$projectVersion" fernapi/fern-typescript:"$projectVersion"
            docker push fernapi/fern-typescript:"$projectVersion"

  publish-java-snapshot:
    machine:
      image: ubuntu-2004:current
    environment:
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
      _JAVA_OPTIONS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Xmx8192m
      JAVA_HOME: /opt/java11
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo mkdir -p /opt/java && cd /opt/java && sudo chown -R circleci:circleci .
            curl https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-linux_x64.tar.gz | tar -xzf - -C /opt/java
            sudo ln -s /opt/java/zulu*/ /opt/java11
      - run:
          name: Run code-generation
          command: npx fern-api@0.0.54 generate
      - run:
          name: Publish
          command: |
            export PATH="$PATH:$JAVA_HOME/bin"
            sudo chmod -R 777 packages/api/fern-ir-java/ir-api/model
            cd packages/api/fern-ir-java
            ./gradlew artifactoryPublish

workflows:
  version: 2
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/

      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - check
          context:
            - npm
            - docker-hub

      - publish-java-snapshot:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          context: jfrog
