openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /example:
    get:
      summary: Get Example
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Schema1"
                  - $ref: "#/components/schemas/Schema2"
  /root:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: object
                  properties:
                    foo:
                      type: string
                    inner_bar:
                      type: object
                      properties:
                        foo:
                          type: string
                        bar:
                          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                  bar:
                    type: object
                    properties:
                      foo:
                        type: string
                      inner_bar:
                        type: object
                        properties:
                          foo:
                            type: string
                          bar:
                            type: string

components:
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  schemas:
    Schema1:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Schema2:
      type: object
      properties:
        email:
          type: string
        age:
          type: integer

    RootSchema1:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: object
          properties:
            foo:
              type: string
            inner_bar:
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: string
