types:
  SeedWorkspaceConfiguration:
    properties:
      irVersion: string
      language: Language
      generatorType: GeneratorType
      docker: string
      dockerCommand: optional<string>
      fixtures:
        type: optional<map<string, list<FixtureConfigurations>>>
      compileCommands: optional<list<string>>

  Language:
    enum:
      - python
      - java
      - typescript
      - go

  GeneratorType:
    enum:
      - SDK
      - Model
      - Server

  FixtureConfigurations:
    properties:
      customConfig: unknown
      outputFolder: string
