openapi: 3.0.1
info:
  title: literal-headers
  version: ''
paths:
  /no-headers:
    post:
      operationId: noHeaders_get
      tags:
        - NoHeaders
      parameters: []
      responses:
        '204':
          description: ''
  /only-literal-headers:
    post:
      operationId: onlyLiteralHeaders_get
      tags:
        - OnlyLiteralHeaders
      parameters:
        - name: literalEndpointHeader
          in: header
          required: true
          schema:
            type: string
            enum:
              - endpoint header
          examples:
            Example1:
              value: endpoint header
        - name: falseEndpointHeader
          in: header
          required: true
          schema:
            type: boolean
          examples:
            Example1:
              value: false
      responses:
        '204':
          description: ''
  /with-non-literal-headers:
    post:
      operationId: withNonLiteralHeaders_get
      tags:
        - WithNonLiteralHeaders
      parameters:
        - name: nonLiteralEndpointHeader
          in: header
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: custom header
        - name: literalEndpointHeader
          in: header
          required: true
          schema:
            type: string
            enum:
              - endpoint header
          examples:
            Example1:
              value: endpoint header
        - name: trueEndpointHeader
          in: header
          required: true
          schema:
            type: boolean
          examples:
            Example1:
              value: true
      responses:
        '204':
          description: ''
components:
  schemas: {}
  securitySchemes: {}
