# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

service:
  auth: false
  base-path: ""
  endpoints:
    getWithApiKey:
      auth: true
      docs: GET request with custom api key
      path: /apiKey
      method: GET
      response: string
