name: "Docs Feature Request"
description: "Request a new feature for Fern Docs"
labels: 
  - product/docs
  - feature
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Have a feature idea for Fern Docs? Let us know why it's important and what it should look like!"
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Explain in detail what the feature should do, how it will improve the user experience, and why it is needed. Provide specific examples if possible."
      placeholder: "Describe the feature, its purpose, and the problem it solves..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Provide a specific use case or scenario where this feature would be particularly useful."
      placeholder: "Describe a situation where this feature would be helpful..."
    validations:
      required: true
  - type: textarea
    id: proposed-experience
    attributes:
      label: "Proposed Experience (Optional)"
      description: "If possible, share what the UI or workflow should look like, including examples, diagrams, or screenshots."
      placeholder: "Provide a description, diagram, screenshot, or leave blank if unsure..."
  - type: textarea
    id: alternatives-considered
    attributes:
      label: "Alternatives Considered (Optional)"
      description: "If you've considered other solutions or workarounds, please describe them here."
      placeholder: "Describe any alternative approaches you have thought of or tried..."