name: "Docs Bug Report"
description: "Report a bug with Fern Docs"
labels: 
  - product/docs
  - bug
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Please provide the following details to help us reproduce and fix the issue."
  - type: input
    id: cli-version
    attributes:
      label: "CLI Version (from `fern.config.json`)"
      placeholder: "e.g., 0.44.11"
    validations:
      required: true
  - type: textarea
    id: api-spec
    attributes:
      label: "Minimal API Specification"
      description: "Provide the smallest API spec necessary to reproduce the issue. This helps us quickly understand the context of the bug."
      placeholder: "Paste the API spec here..."
    validations:
      required: true
  - type: textarea
    id: actual-site
    attributes:
      label: "Actual UI Behavior"
      description: "Describe what is currently happening in the UI. If possible, include a screenshot, Loom video, or any other visual aid to help us understand the issue."
      placeholder: "Paste a screenshot, Loom video, or detailed description of the issue here..."
    validations:
      required: true
  - type: textarea
    id: expected-site
    attributes:
      label: "Expected UI Behavior"
      description: "Describe what you expected the UI to do. Providing as much detail as possible helps us understand the difference between expected and actual behavior."
      placeholder: "Describe the expected behavior, including any screenshots or visuals..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue. This helps us replicate the problem on our end."
      placeholder: "1. Go to ...\n2. Click on ...\n3. Observe the issue..."
    validations:
      required: false
  - type: textarea
    id: environment-details
    attributes:
      label: "Environment Details"
      description: "Provide information about your environment, such as browser version, OS, and any other relevant details."
      placeholder: "e.g., Chrome 90, macOS 12.1"
    validations:
      required: false