name: "Documentation Issue"
description: "Report an issue or suggest an improvement for the documentation"
labels: 
  - documentation
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Help us improve our documentation by reporting an issue or suggesting an enhancement."
  - type: input
    id: page-url
    attributes:
      label: "Documentation Page URL"
      description: "Provide the URL of the documentation page where you found the issue."
      placeholder: "e.g., https://buildwithfern.com/learn/your-page"
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Issue Description"
      description: "Describe the issue or improvement in detail. Include any errors, inconsistencies, or areas of confusion."
      placeholder: "Describe the issue here..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce (Optional)"
      description: "Provide clear steps to help us reproduce the issue. This will help us understand the problem more easily."
      placeholder: "1. Go to the page...\n2. Click on...\n3. Observe the issue..."
  - type: textarea
    id: suggested-improvement
    attributes:
      label: "Suggested Improvement"
      description: "Propose how the documentation could be improved. Include specific changes or additional information that could be helpful."
      placeholder: "Suggest an improvement or leave blank if unsure..."