name: "Other Issue"
description: "Report any other issue or share feedback not covered by other templates"
labels: 
  - other
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Have something to report that doesn't fit into any of our other categories? Share it here!"
  - type: textarea
    id: issue-description
    attributes:
      label: "Issue Description"
      description: "Provide a detailed description of the issue or feedback you want to share."
      placeholder: "Describe the issue or feedback here..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context (Optional)"
      description: "Include any relevant details, links, or attachments that might help us understand the issue better."
      placeholder: "Provide any additional context here..."