name: "SDK Feature Request"
description: "Request a new feature for the SDK generator"
labels: 
  - product/sdk-generator
  - feature
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Have a feature idea? Tell us why you want it and what it might look like!"
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Explain what the feature should do and why it would be useful."
      placeholder: "Describe the feature and its purpose here..."
    validations:
      required: true
  - type: textarea
    id: proposed-code
    attributes:
      label: "Proposed Generated Code (Optional)"
      description: "If possible, share what you think the generated code should look like."
      placeholder: "Provide a code example or leave blank if unsure..."