name: "SDK Bug Report"
description: "Report a bug with the Fern SDK generator"
labels: 
  - product/sdk-generator
  - bug
assignees: dsheridan
body:
  - type: markdown
    attributes:
      value: "Please provide the following details to help us reproduce and fix the issue."
  - type: input
    id: cli-version
    attributes:
      label: "CLI Version from `fern.config.json`"
      placeholder: "e.g., 0.44.11"
    validations:
      required: true
  - type: input
    id: generator-version
    attributes:
      label: "Generator & Version from `generators.yml`"
      placeholder: "e.g., fernapi/fern-typescript-node-sdk 0.9.5"
    validations:
      required: true
  - type: textarea
    id: api-spec
    attributes:
      label: "Minimal API Specification"
      description: "Provide the smallest API spec necessary to reproduce the issue. This will help us quickly understand the context of the bug."
      placeholder: "Paste the API spec here..."
    validations:
      required: true
  - type: textarea
    id: actual-code
    attributes:
      label: "Actual Generated Code"
      description: "Include a snippet of the code that was generated. Providing code samples helps us identify the issue faster."
      placeholder: "Paste the actual generated code here..."
    validations:
      required: true
  - type: textarea
    id: expected-code
    attributes:
      label: "Expected Generated Code"
      description: "Provide an example of what you expected the generated code to look like."
      placeholder: "Paste the expected code here..."
    validations:
      required: true
  - type: textarea
    id: environment-details
    attributes:
      label: "Environment Details (Optional)"
      description: "Provide any relevant information about your environment, such as operating system, Node.js version, etc."
      placeholder: "e.g., macOS 12.3, Node.js 16.4.2"