openapi: 3.0.1
info:
  title: undiscriminated-unions
  version: ''
paths:
  /:
    post:
      operationId: union_get
      tags:
        - Union
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyUnion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyUnion'
components:
  schemas:
    MyUnion:
      title: MyUnion
      oneOf:
        - type: string
        - type: array
          items:
            type: string
        - type: integer
        - type: array
          items:
            type: integer
        - type: array
          items:
            type: array
            items:
              type: integer
        - type: array
          items:
            type: string
      description: Several different types are accepted.
  securitySchemes: {}
