openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /users:
    post:
      operationId: user_createUser
      tags:
        - User
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  nullable: true
                age:
                  type: integer
                  nullable: true
                weight:
                  type: number
                  format: double
                  nullable: true
              required:
                - username
    get:
      operationId: user_getUser
      tags:
        - User
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: age
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: weight
          in: query
          required: false
          schema:
            type: number
            format: double
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Metadata:
      title: Metadata
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MetadataValue'
        nullable: true
    MetadataValue:
      title: MetadataValue
      oneOf:
        - type: number
          format: double
        - type: string
        - type: boolean
        - type: array
          items:
            $ref: '#/components/schemas/MetadataValue'
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
          nullable: true
        age:
          type: integer
          nullable: true
        weight:
          type: number
          format: double
          nullable: true
        metadata:
          $ref: '#/components/schemas/Metadata'
          nullable: true
      required:
        - id
        - username
    CreateUserResponse:
      title: CreateUserResponse
      type: object
      properties:
        userId:
          type: string
      required:
        - userId
  securitySchemes: {}
