imports:
  root: __package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    metrics-devrev-ingest:
      path: /metrics.devrev.ingest
      method: POST
      auth: true
      docs: Ingest endpoint for DevRev metrics data from clients.
      request:
        name: MetricsDataIngestRequest
        body:
          properties:
            metrics:
              docs: Metrics data received from Dev orgs.
              type: list<root.MetricsData>
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
      examples:
        - request:
            metrics:
              - data_points:
                  - timestamp: '2023-01-01T12:00:00Z'
                    value: 1.1
                name: name
                org_ref: org_ref
    uoms-create:
      path: /uoms.create
      method: POST
      auth: true
      docs: Creates a Unit of Measurement on a part.
      request:
        name: UomsCreateRequest
        body:
          properties:
            aggregation_detail: root.AggregationDetail
            description:
              docs: Description of the Unit of Measurement (UOM).
              type: optional<string>
            dimensions:
              docs: >
                The list of dimensions that can be emitted as part of metrics
                data.

                Dimensions consist of list of key-value pairs. For example, if
                the

                UOM is 'number_of_api_calls', then dimensions can be
                ['api_name',

                'api_version'].Dimension keys can only contain alphanumeric

                characters (A-Z, a-z, and 0-9) and underscores (_). Dimension
                keys

                cannot start with a number and is case-insensitive.Dimension
                keys

                must be unique and it is not allowed to have more than one value

                with the same key.Metrics data ingested in DevRev metrics format

                will be grouped and aggregated based on the dimensions specified
                in

                UOM.
              type: optional<list<string>>
            metric_name:
              type: string
              docs: >
                Name of the Unit of Measurement (UOM). Unit of Measurement is a

                unit of measure defined over a part offered by a Dev Org. A
                single

                part can have multiple unit of measurements defined over it. For

                example, a part can be 'video call', one UOM defined on this can
                be

                'number_of_calls', other UOM can be 'call_duration' etc.Metric
                name

                should be unique across all UOMs in a Dev Org.Metric name can
                only

                contain alphanumeric characters (A-Z, a-z, and 0-9) and
                underscores

                (_). Metric name cannot start with a number and is

                case-insensitive.
            name:
              type: string
              docs: Human readable name of the Unit of Measurement (UOM).
            part_id:
              docs: |
                The part ID for which the Unit of Measurement (UOM) is defined.
                When defined, ingested metrics data will be associated with part
                and product specified in UOM.
              type: optional<string>
            product_id:
              type: string
              docs: >
                The product ID for which the Unit of Measurement (UOM) is
                defined.
            unit: root.unit
      response:
        docs: Success.
        type: root.UomsCreateResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
    uoms-delete:
      path: /uoms.delete
      method: POST
      auth: true
      docs: Deletes a Unit of Measurement.
      request:
        name: UomsDeleteRequest
        body:
          properties:
            id:
              type: string
              docs: The Unit of Measurement (UOM)'s DON.
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.NotFoundError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
      examples:
        - request:
            id: id
    uoms-get:
      path: /uoms.get
      method: GET
      auth: true
      docs: Gets a Unit of Measurement.
      request:
        name: UomsGetQuery
        query-parameters:
          id:
            type: string
            docs: The Unit of Measurement (UOM)'s DON.
      response:
        docs: Success.
        type: root.UomsGetResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.NotFoundError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
    uoms-get-post:
      path: /uoms.get
      method: POST
      auth: true
      docs: Gets a Unit of Measurement.
      request:
        name: UomsGetRequest
        body:
          properties:
            id:
              type: string
              docs: The Unit of Measurement (UOM)'s DON.
      response:
        docs: Success.
        type: root.UomsGetResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.NotFoundError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
    uoms-list:
      path: /uoms.list
      method: GET
      auth: true
      docs: Gets the Unit of Measurements based on the given filters.
      request:
        name: UomsListQuery
        query-parameters:
          aggregation_types:
            type: optional<root.AggregationDetailAggregationType>
            allow-multiple: true
            docs: List of aggregation types for filtering list of UOMs.
          cursor:
            type: optional<string>
            docs: >
              The cursor to resume iteration from. If not provided, then
              iteration

              starts from the beginning.
          ids:
            type: optional<string>
            allow-multiple: true
            docs: |
              List of Unit of Measurement (UOM) DONs to be used in filtering
              complete list of UOMs defined in a Dev Org.
          limit:
            type: optional<integer>
            docs: >
              The maximum number of UOMs to be returned in a response. The
              default

              is '50'.
          metric_names:
            type: optional<string>
            allow-multiple: true
            docs: List of metric names for filtering list of UOMs.
          mode:
            type: optional<root.ListMode>
            docs: |
              The iteration mode to use, otherwise if not set, then "after" is
              used.
          part_ids:
            type: optional<string>
            allow-multiple: true
            docs: List of part IDs for filtering list of UOMs.
          product_ids:
            type: optional<string>
            allow-multiple: true
            docs: List of product IDs for filtering list of UOMs.
          sort_by:
            type: optional<string>
            allow-multiple: true
            docs: >
              Fields to sort the Unit Of Measuments (UOMs) by and the direction
              to

              sort them.
          unit_types:
            type: optional<root.UnitType>
            allow-multiple: true
            docs: List of unit types for filtering list of UOMs.
      response:
        docs: Success.
        type: root.UomsListResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
      examples:
        - response:
            body:
              next_cursor: next_cursor
              prev_cursor: prev_cursor
              uoms: []
    uoms-list-post:
      path: /uoms.list
      method: POST
      auth: true
      docs: Gets the Unit of Measurements based on the given filters.
      request:
        name: UomsListRequest
        body:
          properties:
            aggregation_types:
              docs: List of aggregation types for filtering list of UOMs.
              type: optional<list<root.AggregationDetailAggregationType>>
            cursor:
              docs: |
                The cursor to resume iteration from. If not provided, then
                iteration starts from the beginning.
              type: optional<string>
            ids:
              docs: |
                List of Unit of Measurement (UOM) DONs to be used in filtering
                complete list of UOMs defined in a Dev Org.
              type: optional<list<string>>
            limit:
              docs: |
                The maximum number of UOMs to be returned in a response. The
                default is '50'.
              type: optional<integer>
            metric_names:
              docs: List of metric names for filtering list of UOMs.
              type: optional<list<string>>
            mode: optional<root.ListMode>
            part_ids:
              docs: List of part IDs for filtering list of UOMs.
              type: optional<list<string>>
            product_ids:
              docs: List of product IDs for filtering list of UOMs.
              type: optional<list<string>>
            sort_by:
              docs: >
                Fields to sort the Unit Of Measuments (UOMs) by and the
                direction

                to sort them.
              type: optional<list<string>>
            unit_types:
              docs: List of unit types for filtering list of UOMs.
              type: optional<list<root.UnitType>>
      response:
        docs: Success.
        type: root.UomsListResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
      examples:
        - request: {}
          response:
            body:
              next_cursor: next_cursor
              prev_cursor: prev_cursor
              uoms: []
    uoms-update:
      path: /uoms.update
      method: POST
      auth: true
      docs: Updates a Unit of Measurement.
      request:
        name: UomsUpdateRequest
        body:
          properties:
            aggregation_type: optional<root.AggregationDetailAggregationType>
            description:
              docs: Description of the Unit of Measurement (UOM).
              type: optional<string>
            dimensions: optional<root.UomsUpdateRequestDimensions>
            id:
              type: string
              docs: The Unit of Measurement (UOM)'s DON.
            is_enabled:
              docs: |
                Flag used to enable/disable the Unit of Measurement (UOM). When
                disabled, any metricsrecords ingested against this UOM will be
                dropped.
              type: optional<boolean>
            name:
              docs: Human readable name of the Unit of Measurement (UOM).
              type: optional<string>
            part_id:
              docs: |
                The part ID such as feature or capability for which the Unit of
                Measurement (UOM) is defined.
              type: optional<string>
            product_id:
              docs: >
                The product ID for which the Unit of Measurement (UOM) is
                defined.
              type: optional<string>
            unit:
              docs: Unit name of the Unit of Measurement (UOM).
              type: optional<string>
      response:
        docs: Success.
        type: root.UomsUpdateResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.NotFoundError
        - root.TooManyRequestsError
        - root.InternalServerError
        - root.ServiceUnavailableError
  display-name: product-usage
docs: Product Usage APIs
