openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /test:
    get:
      operationId: svc_test
      tags:
        - Svc
      parameters:
        - name: some-enum
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/myEnum'
              nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    myEnum:
      title: myEnum
      type: string
      enum:
        - one
        - two
        - three
        - four
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
