openapi: 3.0.1
info:
  title: object
  version: ''
paths:
  /root/root:
    post:
      operationId: getRoot
      tags:
        - ''
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootType1'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bar:
                  $ref: '#/components/schemas/InlineType1'
                foo:
                  type: string
              required:
                - bar
                - foo
components:
  schemas:
    RootType1:
      title: RootType1
      type: object
      properties:
        foo:
          type: string
        bar:
          $ref: '#/components/schemas/InlineType1'
      required:
        - foo
        - bar
    InlineType1:
      title: InlineType1
      type: object
      properties:
        foo:
          type: string
        bar:
          $ref: '#/components/schemas/NestedInlineType1'
      required:
        - foo
        - bar
    InlineType2:
      title: InlineType2
      type: object
      properties:
        baz:
          type: string
      required:
        - baz
    NestedInlineType1:
      title: NestedInlineType1
      type: object
      properties:
        foo:
          type: string
        bar:
          type: string
        myEnum:
          $ref: '#/components/schemas/InlineEnum'
      required:
        - foo
        - bar
        - myEnum
    InlinedDiscriminatedUnion1:
      title: InlinedDiscriminatedUnion1
      oneOf:
        - type: object
          allOf:
            - type: object
              properties:
                type:
                  type: string
                  enum:
                    - type1
            - $ref: '#/components/schemas/InlineType1'
          required:
            - type
        - type: object
          allOf:
            - type: object
              properties:
                type:
                  type: string
                  enum:
                    - type2
            - $ref: '#/components/schemas/InlineType2'
          required:
            - type
    InlinedUndiscriminatedUnion1:
      title: InlinedUndiscriminatedUnion1
      oneOf:
        - $ref: '#/components/schemas/InlineType1'
        - $ref: '#/components/schemas/InlineType2'
    InlineEnum:
      title: InlineEnum
      type: string
      enum:
        - SUNNY
        - CLOUDY
        - RAINING
        - SNOWING
  securitySchemes: {}
