service:
  auth: false
  base-path: "/{serviceParasdfm}"
  path-parameters:
    serviceParasdfm: string
  endpoints:
    post:
      path: "/{endpointParam}/{resourceParam}"
      path-parameters:
        resourceParam: string
        endpointParam: integer
      method: POST
