# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

ids:
  - TaskId
types:
  GeneratorConfig:
    properties:
      irFilepath: string
      output: GeneratorOutputConfig
      publish: optional<GeneratorPublishConfig>
      workspaceName: string
      organization: string
      customConfig: unknown
      environment: GeneratorEnvironment
  GeneratorOutputConfig:
    properties:
      path: string
  GeneratorPublishConfig:
    properties:
      registries: GeneratorRegistriesConfig
      version: string
  GeneratorRegistriesConfig:
    properties:
      maven: MavenRegistryConfig
      npm: NpmRegistryConfig
  MavenRegistryConfig:
    properties:
      registryUrl: string
      username: string
      password: string
      group: string
  NpmRegistryConfig:
    properties:
      registryUrl: string
      token: string
      scope: string
  GeneratorEnvironment:
    union:
      local: {}
      remote: RemoteGeneratorEnvironment
  RemoteGeneratorEnvironment:
    properties:
      coordinatorUrl: string
      id: TaskId
