openapi: 3.0.1
info:
  title: enum
  version: ''
paths:
  /inlined:
    post:
      operationId: inlinedRequest_send
      tags:
        - InlinedRequest
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operand:
                  $ref: '#/components/schemas/Operand'
                maybeOperand:
                  $ref: '#/components/schemas/Operand'
                  nullable: true
                operandOrColor:
                  $ref: '#/components/schemas/ColorOrOperand'
                maybeOperandOrColor:
                  $ref: '#/components/schemas/ColorOrOperand'
                  nullable: true
              required:
                - operand
                - operandOrColor
            examples:
              Example1:
                value:
                  operand: '>'
  /path/{operand}/{maybeOperand}/{operandOrColor}/{maybeOperandOrColor}:
    post:
      operationId: pathParam_send
      tags:
        - PathParam
      parameters:
        - name: operand
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Operand'
          examples:
            Example1:
              value: '>'
        - name: maybeOperand
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Operand'
            nullable: true
        - name: operandOrColor
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ColorOrOperand'
        - name: maybeOperandOrColor
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ColorOrOperand'
            nullable: true
      responses:
        '204':
          description: ''
  /query:
    post:
      operationId: queryParam_send
      tags:
        - QueryParam
      parameters:
        - name: operand
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Operand'
          examples:
            Example1:
              value: '>'
        - name: maybeOperand
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Operand'
            nullable: true
      responses:
        '204':
          description: ''
  /query-list:
    post:
      operationId: queryParam_sendList
      tags:
        - QueryParam
      parameters:
        - name: operand
          in: query
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Operand'
        - name: maybeOperand
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Operand'
              nullable: true
      responses:
        '204':
          description: ''
components:
  schemas:
    Operand:
      title: Operand
      type: string
      enum:
        - '>'
        - '='
        - less_than
      description: |-
        Tests enum name and value can be
        different.
    Color:
      title: Color
      type: string
      enum:
        - red
        - blue
    ColorOrOperand:
      title: ColorOrOperand
      oneOf:
        - type: object
          properties:
            type:
              type: string
              enum:
                - color
            value:
              $ref: '#/components/schemas/Color'
          required:
            - type
        - type: object
          properties:
            type:
              type: string
              enum:
                - operand
            value:
              $ref: '#/components/schemas/Operand'
          required:
            - type
  securitySchemes: {}
