types:
  Object:
    properties:
      id: string

  Response:
    properties:
      data: Object

service:
  auth: false
  base-path: ""
  endpoints:
    getObject:
      method: POST
      path: /object
      request: string
      response:
        type: Response
        responseBodyProperty: data
