name: CI

on: [push]

env:
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  MSBUILDTERMINALLOGGER: off

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: List SDKs
        run: dotnet --list-sdks

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build release
        id: build
        run: dotnet build src -c Release /p:ContinuousIntegrationBuild=true

      - name: Run tests
        run: dotnet test src --no-restore --no-build -c Release /p:ContinuousIntegrationBuild=true
        continue-on-error: true

      - name: Publish to nuget.org
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && steps.build.outcome == 'success'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_TOKEN }}
        run: |
          dotnet pack src/SeedExhaustive --no-build --no-restore -c Release
          dotnet nuget push src/SeedExhaustive/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source "nuget.org"
