openapi: 3.0.3
info:
  title: Test API
  version: 1.0.0
servers:
  - url: https://localhost
tags:
  - name: dataservice
paths:
  /foo:
    post:
      tag: dataservice
      x-fern-sdk-group-name:
        - dataservice
      x-fern-sdk-method-name: foo
      security:
        - ApiKeyAuth: []
      operationId: foo
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object

security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
