openapi: 3.0.1
info:
  title: file-upload
  version: ''
paths:
  /:
    post:
      operationId: service_post
      tags:
        - Service
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                maybeString:
                  type: string
                  nullable: true
                integer:
                  type: integer
                file:
                  type: string
                  format: binary
                fileList:
                  type: string
                  format: binary
                maybeFile:
                  type: string
                  format: binary
                maybeFileList:
                  type: string
                  format: binary
                maybeInteger:
                  type: integer
                  nullable: true
                optionalListOfStrings:
                  type: array
                  items:
                    type: string
                  nullable: true
                listOfObjects:
                  type: array
                  items:
                    $ref: '#/components/schemas/MyObject'
                optionalMetadata:
                  nullable: true
                optionalObjectType:
                  $ref: '#/components/schemas/ObjectType'
                  nullable: true
                optionalId:
                  $ref: '#/components/schemas/Id'
                  nullable: true
  /just-file:
    post:
      operationId: service_justFile
      tags:
        - Service
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
  /just-file-with-query-params:
    post:
      operationId: service_justFileWithQueryParams
      tags:
        - Service
      parameters:
        - name: maybeString
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: integer
          in: query
          required: true
          schema:
            type: integer
        - name: maybeInteger
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: listOfStrings
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: optionalListOfStrings
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              nullable: true
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
components:
  schemas:
    Id:
      title: Id
      type: string
    MyObject:
      title: MyObject
      type: object
      properties:
        foo:
          type: string
      required:
        - foo
    ObjectType:
      title: ObjectType
      type: string
      enum:
        - FOO
        - BAR
  securitySchemes: {}
