openapi: 3.0.1
info:
  title: file-upload
  version: ''
paths:
  /:
    post:
      operationId: service_post
      tags:
        - Service
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                maybeString:
                  type: string
                  nullable: true
                integer:
                  type: integer
                file:
                  type: string
                  format: binary
                maybeFile:
                  type: string
                  format: binary
                maybeInteger:
                  type: integer
                  nullable: true
                listOfStrings:
                  type: array
                  items:
                    type: string
                setOfStrings:
                  type: array
                  items:
                    type: string
                optionalListOfStrings:
                  type: array
                  items:
                    type: string
                  nullable: true
                optionalSetOfStrings:
                  type: array
                  items:
                    type: string
                  nullable: true
                maybeList:
                  $ref: '#/components/schemas/MaybeList'
                optionalMaybeList:
                  $ref: '#/components/schemas/MaybeList'
                  nullable: true
                maybeListOrSet:
                  $ref: '#/components/schemas/MaybeListOrSet'
                optionalMaybeListOrSet:
                  $ref: '#/components/schemas/MaybeListOrSet'
                  nullable: true
                listOfObjects:
                  type: array
                  items:
                    $ref: '#/components/schemas/MyObject'
  /just-file:
    post:
      operationId: service_justFile
      tags:
        - Service
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
components:
  schemas:
    MaybeList:
      title: MaybeList
      oneOf:
        - type: string
        - type: array
          items:
            type: string
        - type: integer
        - type: array
          items:
            type: integer
        - type: array
          items:
            type: array
            items:
              type: integer
    MaybeListOrSet:
      title: MaybeListOrSet
      oneOf:
        - type: string
        - type: array
          items:
            type: string
        - type: integer
        - type: array
          items:
            type: integer
        - type: array
          items:
            type: array
            items:
              type: integer
        - type: array
          items:
            type: string
    MyObject:
      title: MyObject
      type: object
      properties:
        foo:
          type: string
      required:
        - foo
  securitySchemes: {}
