name: seed-coompile-containers

on:
  push:
    branches:
      - main
      - ab/seedspeed
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      python:  ${{ steps.filter.outputs.python }}
      ts:  ${{ steps.filter.outputs.ts }}
      java:  ${{ steps.filter.outputs.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            python: 
              - 'docker/seed/Dockerfile.python'
              - 'generators/python/poetry.lock'
              - '.github/workflows/build-seed.yml'
            ts: 
              - 'docker/seed/Dockerfile.ts'
              - '.github/workflows/build-seed.yml'
            java: 
              - 'docker/seed/Dockerfile.java'
              - '.github/workflows/build-seed.yml'
  
  python:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.python == 'true' }}
    needs: changes
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fernapi/python-seed
          tags: |
            type=sha
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/seed/Dockerfile.python
          platforms: linux/amd64,linux/arm64
          push: true
          # use short SHA if modded, or just use latest if nothing changed
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  java:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.java == 'true' }}
    needs: changes
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fernapi/java-seed
          tags: |
            type=sha
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/seed/Dockerfile.java
          platforms: linux/amd64,linux/arm64
          push: true
          # use short SHA if modded, or just use latest if nothing changed
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ts:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.ts == 'true' }}
    needs: changes
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fernapi/ts-seed
          tags: |
            type=sha
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/seed/Dockerfile.ts
          platforms: linux/amd64,linux/arm64
          push: true
          # use short SHA if modded, or just use latest if nothing changed
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
