name: fern

on:
  pull_request:
    paths:
      - "fern/**"
    branches:
      - main

jobs:
  check-definitions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Check API definition is valid
        env:
          FORCE_COLOR: "2"
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
        run: |
          yarn workspace @fern-api/cli dist:cli:prod
          cli_path="$(yarn workspace @fern-api/cli bin fern:prod)"
          node $cli_path check

