name: fern

on:
  pull_request:
    paths:
      - "fern/**"
    branches:
      - main

jobs:
  check-ir-definitions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check API definition is valid
        env:
          FORCE_COLOR: "2"
        run: fern check
