name: node-sdk

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Node SDK that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install the Fern CLI
        run: npm install -g fern-api

      - name: Release Node SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
        run: |
          fern generate --api public-api --group node-sdk --version ${{ inputs.version }} --log-level debug
