name: openapi

on:
  push:
    paths:
      - "generators/openapi/VERSION"
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/openapi-generator.yml

  publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Build CLI
        working-directory: ./generators/openapi
        run: yarn dist:cli

      - name: Print Version
        run: |
          projectVersion=$(cat generators/openapi/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/openapi
          file: ./generators/openapi/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-openapi:${{env.VERSION}}
