name: openapi

on:
  workflow_call:
  pull_request:
    paths:
      - "generators/openapi/**"
    branches:
      - main

jobs:
  seed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Install seed
        run: npm install -g @fern-api/seed-cli@0.15.0-rc51

      - name: Test
        working-directory: ./generators/openapi
        run: seed test --workspace openapi --parallel 10

      - name: Ensure no changes to git-tracked files
        working-directory: ./generators/openapi
        run: git --no-pager diff
