name: publish-docs

on:
  push:
    paths:
      - "fern/**"
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
        run: |
          yarn workspace @fern-api/cli dist:cli:prod
          cli_path="$(yarn workspace @fern-api/cli bin fern:prod)"
          node $cli_path generate --docs --log-level debug --instance fern.docs.buildwithfern.com/learn

      # - name: Install fern-dev CLI
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken ${{ secrets.YARN_NPM_AUTH_TOKEN }}
      #     npm install -g @fern-api/fern-api-dev --prefix=$HOME/.local
      
      # - name: Publish Docs to dev
      #   env:
      #     FERN_TOKEN: ${{ secrets.FERN_ORG_TOKEN_DEV }}
      #   run: fern-dev generate --docs --log-level debug  --instance fern.docs.dev.buildwithfern.com/learn
