name: publish-generator
on: workflow_dispatch

jobs:
  # TODO: run seed tests and check
  #   check:
  #     uses: ./.github/workflows/check.yml
  application-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          version=`./scripts/git-version.sh`
          echo "::set-output name=version::$version"

  publish-ruby-sdk-docker:
    runs-on: ubuntu-latest
    needs: application-version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Build and push Ruby Model Docker image
        run: |
          projectVersion=$(./scripts/git-version.sh)
          yarn workspace @fern-api/fern-ruby-model dockerTagVersion "$projectVersion"
          docker push fernapi/fern-ruby-model:"$projectVersion"
