name: Publish CLI

on:
  workflow_call:
    inputs:
      version:
        description: "The version of the CLI to release"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the CLI to release"
        required: true
        type: string

# Add this permissions block
permissions:
  contents: write
  pull-requests: write

jobs:
  live-test:
    environment: Fern Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Check API definition is valid
        env:
          FORCE_COLOR: "2"
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
        run: |
          pnpm --filter @fern-api/cli dist:cli:prod
          cli_path="$(pwd)/packages/cli/cli/dist/prod/bundle.cjs" 
          ./scripts/live-test.sh "$cli_path" "$FERN_TOKEN"

  publish-rc:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install
        uses: ./.github/actions/install

      - name: Print version
        run: |
          git_version=${{ inputs.version }} 
          echo Publishing version: "${git_version}"

      - name: Add version to dev package.json's
        run: |
          git_version=${{ inputs.version }} 
          
          cd packages/cli/cli
          mv package.json package.json.tmp
          version_replace="s/0.0.0/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json
          rm -rf package.json.tmp

          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Update pnpm lock with new versions
        run: pnpm install

      - name: Compile
        run: pnpm --filter @fern-api/cli compile

      - name: Publish fern-api CLI
        run: pnpm --filter @fern-api/cli publish:cli:prod --tag prerelease

  publish:
    needs: live-test
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install
        uses: ./.github/actions/install

      - name: Print version
        run: |
          git_version=${{ inputs.version }} 
          echo Publishing version: "${git_version}"

      - name: Add version to package.json's
        run: |
          git_version=${{ inputs.version }} 

          cd packages/cli/cli
          mv package.json package.json.tmp
          version_replace="s/0.0.0/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json
          rm -rf package.json.tmp

          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Update pnpm lock with new versions
        run: pnpm install

      - name: Compile
        run: pnpm --filter @fern-api/cli compile

      - name: Publish fern-api CLI
        run: pnpm --filter @fern-api/cli publish:cli:prod --tag latest
