name: Publish @fern-api/go-dynamic-snippets 

on:
  push:
    branches:
      - amckinney/go/npm
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the library to publish."
        required: true
        type: string

env:
  PACKAGE_NAME: "@fern-api/go-dynamic-snippets"
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}

jobs:
  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: 📥 Install
        uses: ./.github/actions/install

      - uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install protoc-gen-openapi
        run: go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.7.0

      - name: 🧪 Build
        run: pnpm --filter=${{ env.PACKAGE_NAME }} compile

      - name: 🧪 Test
        run: pnpm --filter=${{ env.PACKAGE_NAME }} test

      - name: Publish @fern-api/go-dynamic-snippets
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm --filter=${{ env.PACKAGE_NAME }} dist 0.0.1
          cd dist
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public

  publish-manually:
    runs-on: ubuntu-latest
    if: ${{ inputs.version != null }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: 📥 Install
        uses: ./.github/actions/install

      - uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install protoc-gen-openapi
        run: go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.7.0

      - name: 🧪 Build
        run: pnpm --filter=${{ env.PACKAGE_NAME }} compile

      - name: 🧪 Test
        run: pnpm --filter=${{ env.PACKAGE_NAME }} test

      - name: Publish @fern-api/go-dynamic-snippets
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd generators/go-v2/dynamic-snippets
          pnpm --filter=${{ env.PACKAGE_NAME }} dist ${{ inputs.version }}
          cd dist
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public