name: python-sdk

on:
  push:
    paths:
      - "generators/python/sdk/VERSION"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install
        working-directory: ./generators/python
        run: poetry install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Print Version
        run: |
          projectVersion=$(cat generators/python/sdk/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/python
          file: ./generators/python/sdk/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-python-sdk:${{env.VERSION}}
