name: seed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      seed: ${{ steps.filter.outputs.seed }}
      ruby: ${{ steps.filter.outputs.ruby }}
      openapi: ${{ steps.filter.outputs.openapi }}
      python: ${{ steps.filter.outputs.python }}
      postman: ${{ steps.filter.outputs.postman }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            seed: 
              - 'packages/seed/**'
              - 'test-definitions/**'
            ruby: 'generators/ruby/**'
            openapi: 'generators/openapi/**'
            python: 'generators/python/**'
            postman: 'generators/postman/**'

  ruby-model:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.ruby == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install Seed
        run: npm install -g @fern-api/seed-cli

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace ruby-model --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  pydantic-model:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace pydantic --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  python-sdk:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace sdk --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  fastapi:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace fastapi --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  openapi:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.openapi == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace openapi --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  postman:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.postman == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace postman --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
