name: Setup Seed

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - uses: bufbuild/buf-setup-action@v1.34.0

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install protoc-gen-openapi
        run: go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.7.0
