name: test-definitions

on:
  pull_request:
    branches:
      - main

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Deps
        run: yarn install

      - name: Fern check
        run: |
          yarn workspace @fern-api/cli dist:cli:dev
          cd test-definitions
          FERN_NO_VERSION_REDIRECTION=true node $(yarn workspace @fern-api/cli bin fern:dev) check
