name: test-docs-generation

on: pull_request
  # push:
  #   paths:
  #     - "fern/packages/cli/**"
  #     - "fern/packages/core/**"
  #     - "fern/packages/commons/**"
  #     - ".github/workflows/publish-docs.yml"
  #   branches:
  #     - main

jobs:
  run:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Clone the Cohere Developer Experience repo
        run: |
          git clone https://github.com/cohere-ai/cohere-developer-experience.git
          cd cohere-developer-experience
          echo "Cohere Developer Experience repo cloned successfully!"

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
        run: |
          pnpm --filter @fern-api/cli dist:cli:prod
          cli_path="$(pwd)/packages/cli/cli/dist/prod/cli.cjs" 
          node $cli_path generate --docs --preview --log-level debug 