name: changelog

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate cli --log-level debug

  fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate generator fastapi --log-level debug

  pydantic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate generator pydantic --log-level debug

  python-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate generator python-sdk --log-level debug

  go-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate generator go-sdk --log-level debug

  ruby-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Validate changelog
        run: |
          pnpm seed:local validate generator ruby-sdk --log-level debug
