types:
  WithDocs:
    properties:
      docs: string

  Object:
    properties:
      id: string

  Response:
    extends:
      - WithDocs
    properties:
      data: Object

service:
  auth: false
  base-path: ""
  endpoints:
    getObject:
      method: POST
      path: /object
      request: string
      response:
        type: Response
        response-property: data

    getObjectDocs:
      method: POST
      path: /object
      request: string
      response:
        type: Response
        response-property: docs
